name: Repo bot-koin airdrop

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      SOURCE_URL:
        description: 'Source URL to clone repositories from'
        required: true
        default: 'https://codeberg.org/smart-airdrop'

  schedule:
    - cron: '0 0 * * *'  # Jalan setiap hari jam 00:00 UTC

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y jq git

      - name: Extract source domain and organization
        run: |
          SOURCE_URL="${{ github.event.inputs.SOURCE_URL }}"
          echo "Using SOURCE_URL: $SOURCE_URL"
          
          # Ekstrak domain dan user/org dari URL
          DOMAIN=$(echo "$SOURCE_URL" | awk -F/ '{print $3}')
          ORG=$(echo "$SOURCE_URL" | awk -F/ '{print $4}')
          
          echo "Extracted DOMAIN: $DOMAIN"
          echo "Extracted ORG: $ORG"

          # Simpan di environment agar bisa dipakai di step berikutnya
          echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
          echo "ORG=$ORG" >> $GITHUB_ENV

      - name: Get repository list from source
        run: |
          if [[ "$DOMAIN" == "codeberg.org" ]]; then
            API_URL="https://codeberg.org/api/v1/users/$ORG/repos"
          elif [[ "$DOMAIN" == "github.com" ]]; then
            API_URL="https://api.github.com/users/$ORG/repos"
          else
            echo "Unsupported domain: $DOMAIN"
            exit 1
          fi

          echo "Fetching repository list from $API_URL..."
          response=$(curl -s -H "Accept: application/json" "$API_URL")
      
          if echo "$response" | jq empty 2>/dev/null; then
            repos=$(echo "$response" | jq -r '.[].name')
            echo "$repos" > repo_list.txt
            echo "REPO_LIST=$(echo "$repos" | tr '\n' ' ')" >> $GITHUB_ENV
          else
            echo "Error: Response is not a valid JSON"
            echo "Response: $response"
            exit 1
          fi

      - name: Clone repositories from source
        run: |
          mkdir repos && cd repos
          for repo in $(cat ../repo_list.txt); do
            echo "Cloning $repo..."
            git clone --depth=1 "https://$DOMAIN/$ORG/$repo.git" "$repo" || echo "Failed to clone $repo"
          done

      - name: Clean repositories (Remove .git and hidden files)
        run: |
          cd repos
          for repo in *; do
            echo "Cleaning repository: $repo"
            rm -rf "$repo/.git" "$repo/.github" "$repo/.gitignore"
          done

      - name: Copy repos to main directory
        run: |
          rm -rf old_repos
          mv repos old_repos
          mkdir -p repos
          cp -r old_repos/* repos/

      - name: Generate README.md
        run: |
          echo "# List of Repositories" > README.md
          echo "" >> README.md
          for repo in $(cat repo_list.txt); do
            echo "- [$repo](https://github.com/rbbaprianto/bot-koin/tree/main/repos/$repo)" >> README.md
          done

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
    
      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin git@github.com:rbbaprianto/bot-koin.git
      
          # Tarik perubahan terbaru dari remote dengan rebase untuk menghindari konflik
          git pull --rebase origin main || echo "No remote changes"
      
          # Tambahkan dan commit perubahan
          git add README.md repos/
          git commit -m "Update repos and README" || echo "No changes to commit"
      
          # Push ke repository
          GIT_SSH_COMMAND="ssh -v" git push origin main

      - name: Send Telegram Notification
        run: |
          escape_markdown() {
            echo "$1" | perl -pe 's/([_*\[\]()~`>#+\-=|{}.!])/\\$1/g'
          }
      
          SOURCE_URL="${{ github.event.inputs.SOURCE_URL }}"
      
          MESSAGE=$'✅ *Repository Sync Completed\\!*\n\n'
          MESSAGE+=$'📌 *Source:* ['"$(escape_markdown "$SOURCE_URL")"']('"$SOURCE_URL"$')\n'
          MESSAGE+=$'📂 *Target:* [GitHub](https://github.com/rbbaprianto/bot-koin)\n\n'
          MESSAGE+=$'📜 *List of Repositories:*\n'
      
          while IFS= read -r repo; do
            ESCAPED_REPO=$(escape_markdown "$repo")
            MESSAGE+=$'🔹 '"$ESCAPED_REPO"$'\n'
          done < repo_list.txt
      
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "message_thread_id=144" \
            -d "text=${MESSAGE}" \
            -d "parse_mode=MarkdownV2"
